name: 'GitOps Update'
description: 'Updates a key in a gitops repository and commit it'
inputs:
  filename:
    description: 'Filename to update'
    required: true
  yq_key:  
    description: "The key to update. Key a string before the colon. Usually it's yaml key like `this-is-key: value`"
    required: true
  yq_value:  
    description: "The value to set"
    required: true
  github-deploy-secret:  
    description: "Github deploy ssh private key to clone and commit target repository"
    required: true
  github-repo:  
    description: "Target organization and repository in form of `some-org/repo`"
    required: true
  github-branch:  
    description: "Target git branch (not support yet)"
    default: 'main'
    required: false
  git-message:  
    description: "Message for commit"
    default: 'GitOpt update'
    required: false
runs:
  using: "composite"
  steps:
  - name: Setup SSH Keys and known_hosts
    env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    shell: bash
    run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ inputs.github-deploy-secret }}"
  - name: Expose git commit data
    uses: rlespinasse/git-commit-data-action@v1
  - uses: actions/checkout@v3
    with:
      repository: ${{ inputs.github-repo }}
      ref: ${{ inputs.github-branch }}
      ssh-key: ${{ inputs.github-deploy-secret }}
      path: ./infra-as-code-repo
      submodules: recursive
  - name: YQ update file
    uses: mikefarah/yq@master
    with:
      cmd: yq '${{ inputs.yq_key }} = "${{ inputs.yq_value }}"' './infra-as-code-repo/${{ inputs.filename }}'
  - name: Setup SSH Keys and known_hosts
    env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    shell: bash
    run: |
      git config --global user.name ${{ env.GIT_COMMIT_AUTHOR_NAME }}
      git config --global user.email ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
      git -C ./infra-as-code-repo commit --all --message '${{ inputs.git-message }}'
      git -C ./infra-as-code-repo push